state_dir: /storage
container_image: ghcr.io/tyzbit/kairos-distros:debian-v3.3.2-v1.31.6k3s1-262
# container_image: ghcr.io/tyzbit/kairos-distros:debian-v3.5.4-v1.34.1k3s1-269
# container_image: quay.io/kairos/debian:12-standard-amd64-generic-v3.5.6-k3s-v1.34.1-k3s1
